#!/usr/bin/env python3
"""Gzip the web SPA sources and embed them in flash as a generated C header.

Runs as a PlatformIO pre-build script (extra_scripts = pre:scripts/gen_web_assets.py)
and also standalone (python scripts/gen_web_assets.py). Each asset becomes a
`static const uint8_t <name>Gz[]` byte array plus a `<name>GzLen`, included only
by ConfigPortal.cpp and served with `Content-Encoding: gzip`.

Embedding via a generated source (rather than board_build.embed_files linker
symbols) keeps this portable across the Arduino framework and avoids relying on
platform-specific symbol mangling — same end result: gzipped assets in flash,
no SPIFFS partition, OTA untouched.
"""
import gzip
import os


def _project_root():
    # When invoked by PlatformIO, `Import`/`env` are injected by SCons and
    # `__file__` is undefined; fall back to the script path when run standalone.
    try:
        Import("env")  # noqa: F821 (provided by SCons)
        return env.subst("$PROJECT_DIR")  # noqa: F821
    except Exception:
        pass
    try:
        return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    except NameError:
        return os.getcwd()


ROOT = _project_root()
SRC = os.path.join(ROOT, "web", "src")
OUT = os.path.join(ROOT, "include", "web_assets.h")

# (source file, C identifier prefix)
ASSETS = [
    ("app.html", "kAppHtml"),
    ("app.css", "kAppCss"),
    ("app.js", "kAppJs"),
]


def newest_source_mtime():
    return max(os.path.getmtime(os.path.join(SRC, f)) for f, _ in ASSETS)


def up_to_date():
    return os.path.exists(OUT) and os.path.getmtime(OUT) >= newest_source_mtime()


def generate():
    out = [
        "// AUTO-GENERATED by scripts/gen_web_assets.py — do not edit by hand.",
        "// Gzipped web SPA assets embedded in flash (served Content-Encoding: gzip).",
        "#ifndef WEB_ASSETS_H",
        "#define WEB_ASSETS_H",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
    ]
    for fname, var in ASSETS:
        with open(os.path.join(SRC, fname), "rb") as fp:
            raw = fp.read()
        gz = gzip.compress(raw, compresslevel=9, mtime=0)  # mtime=0 -> deterministic
        body = ",".join(str(b) for b in gz)
        out.append("static const uint8_t %sGz[] = {%s};" % (var, body))
        out.append("static const size_t %sGzLen = sizeof(%sGz);" % (var, var))
        out.append("")
        print("[web] %-9s %5d B -> %5d B gz" % (fname, len(raw), len(gz)))
    out.append("#endif  // WEB_ASSETS_H")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fp:
        fp.write("\n".join(out) + "\n")
    print("[web] wrote", os.path.relpath(OUT, ROOT))


def main():
    if up_to_date():
        print("[web] assets up to date")
        return
    generate()


main()
